const projectOrganizationEnums = Object.freeze({
  '': '',
  AIS: 'AIS',
  BPS: 'BPS',
  CPL: 'CPL',
  IBS: 'IBS',
  ITE: 'ITE',
  MCS: 'MCS',
  'Banking And Payment': 'Banking and Payment',
  'Enterprise & Cybersecurity': 'Enterprise & Cybersecurity',
  Government: 'Government',
  'Mobile Services & IoT': 'Mobile Services & IoT',
  'R&D Issuance Solutions & Services': 'R&D Issuance Solutions & Services',
  SHD: 'SHD',
  Netsize: 'Netsize',
  IDSS: 'IDSS',
  'Software House': 'Software House',
  GGS: 'GGS',
  ICS: 'ICS',
  Coesys: 'Coesys',
  eBanking: 'eBanking',
  PSE: 'PSE',
});

module.exports = { projectOrganizationEnums };
