name: frontend

on:
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '26.3.1'

      - name: Install lib dependencies
        run: npm install
        working-directory: lib

      - name: Install app dependencies
        run: npm install
        working-directory: app

      - name: Check for Playwright tests
        id: check_tests
        shell: pwsh
        working-directory: app
        run: |
          $tests = Get-ChildItem -Path test -Include *.spec.js,*.test.js -Recurse -ErrorAction SilentlyContinue

          if ($tests) {
            "has_tests=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          } else {
            "has_tests=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          }

      - name: Run Playwright tests
        if: steps.check_tests.outputs.has_tests == 'true'
        run: npm run test
        working-directory: app

      - name: Skip Playwright tests
        if: steps.check_tests.outputs.has_tests == 'false'
        run: echo "No Playwright tests found. Skipping."